### ISSUE TITLE
Pusher hangs when calling `trigger` on AWS Lambda (and other serverless environments)

### ISSUE THREAD

**Issue by steezeburger** [pusher/pusher-http-node#67]
Are there any caveats to getting Pusher running in AWS Lambda? For some reason, my Lambda methods hang at the trigger call and time out.

**Comment by alexvazquez** [comment]
Any clue?

**Comment by gcphost** [comment]
Mine eventually trigger but with the incorrect data. 

Pusher is acting really weird for me on Lambda :(

**Comment by gcphost** [comment]
AWS has upgraded their node version since I last tested, it may no longer be an issue.

**Comment by leesio** [comment]
I ran the below on all 3 versions of node available on lambda at the moment (`4.3`, `6.10` and `8.10`) and didn't notice anything unusual. 

```
exports.handler = function(event, context) {
  var Pusher = require('pusher');
  var pusher = new Pusher({
    appId: process.env.APP_ID,
    key: process.env.KEY,
    secret: process.env.SECRET,
    cluster: process.env.CLUSTER,
    encrypted: true,
  });

  var msg = {message: 'hello-world'};
  pusher.trigger('channel', 'my-event', msg);
  pusher.trigger(['channel-1', 'channel-2'], 'my-event', msg);
  pusher.triggerBatch([
    {
      channel: 'batch1',
      name: 'my-event',
      data: msg,
    },
    {
      channel: 'batch1',
      name: 'my-event2',
      data: msg,
    },
  ]);
};
```

**Comment by kristiankyvik** [comment]
Experiencing the same problem!

**Comment by gcphost** [comment]
@kristiankyvik 

I published a package that ended up working for me, I was never able to resolve the issue.

https://github.com/Askedio/pusher-lambda-promise

**Comment by leesio** [comment]
@gcphost great work on the library!

@kristiankyvik I'm still not able to reproduce this issue, are you able to share more information on what you're experiencing? It would be great to resolve it in pusher-http-node too.

**Comment by kristiankyvik** [comment]
@lessio, I tried using the pusher-http-node module to trigger an event in an lambda function running node 10. The trigger worked locally but failed when deployed to AWS. Still not understand why that was the case.

**Comment by kristiankyvik** [comment]
Hi @leesio, I will try to explain my situation again, since the package I started using stopped working. This is the code I have in my lambda:

```
export const handler = async (event, context, callback) => {
  context.callbackWaitsForEmptyEventLoop = false;

  var pusher = new Pusher({
    appId: process.env.PUSHER_APP_ID,
    key: process.env.PUSHER_APP_KEY,
    secret: process.env.PUSHER_APP_SECRET,
    cluster: process.env.PUSHER_APP_CLUSTER,
    encrypted: true,
  });

  try {
    const notification = {
      type: "lab",
      datetime: moment.utc().format(),
    };
   
   pusher.trigger('channel-name', 'event-name', JSON.stringify({test: "test"}));
  } catch(err) {
    console.log("ERROR", err);
  }

  const response = {
    statusCode: 200,
    headers,
    body: JSON.stringify({
      message: `ok`
    }),
  };

  callback(null, response);
};
```

This works locally, but once deployed on AWS lambda, stops sending events. What am I missing?

**Comment by leesio** [comment]
@kristiankyvik that's interesting.

Does it help if you provide a callback to the trigger function?

```
const response = {
  statusCode: 200,
  headers,
  body: JSON.stringify({
    message: `ok`,
  }),
};
pusher.trigger('channel-name', 'event-name', {test: 'test'}, (err, req, res) => {
  callback(null, response);
});
```

**Comment by benjaminbalazs** [comment]
I am going through the same issue, I can't make trigger work on Lambda. The request comes back with ECONNRESET.

**Comment by benjaminbalazs** [comment]
@farbodsalimi thanks, but promisifying the function also means the original request takes longer to process. That was the reason I was hoping there is a way not to wait for it to fulfill first. Interestingly, it doesn't seem to be possible on Lambda, Lambda somehow cancels the request or freeze the function.

**Comment by alshdavid** [comment]
Using TypeScript this worked nicely for me

```
const triggerAsync = (channel: string, event: string, msg: any) => 
    new Promise((resolve, reject) =>
        pusher.trigger(channel, event, msg, 
            (err, _req, res) => err ? reject(err) : resolve(res)
        ))
```

**Comment by chrisdrackett** [comment]
thanks @alshdavid that worked for me!

**Comment by DomVinyard** [comment]
What a weird bug, a nightmare to track down. thanks @alshdavid

**Comment by fromi** [comment]
I have the same issue with pusher.get to retrieve the members of a presence channel, however the Promise wrapping workaround does not work at all for me...
Any help would be most welcome!

**Comment by lanlin** [comment]
the same problem, any new release?

**Comment by otterji** [comment]
@alshdavid Thanks a lot.......... You made my day ! 🥳

**Comment by callum-oakley** [comment]
This should be fixed in v4.0.0 since `pusher.trigger` now returns a promise, so you can

```js
await pusher.trigger(channel, event, data)
```

**Comment by jameshfisher** [comment]
❤
